<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<GenerateDocumentationFile>True</GenerateDocumentationFile>-->
    <OutputPath>..\lib</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="VL.Core" Version="2025.7.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="IDSImaging.Peak.API">
      <HintPath>..\lib\net8.0\IDSImaging.Peak.API.dll</HintPath>
    </Reference>
    <Reference Include="IDSImaging.Peak.Common">
      <HintPath>..\lib\net8.0\IDSImaging.Peak.Common.dll</HintPath>
    </Reference>
    <Reference Include="IDSImaging.Peak.IPL">
      <HintPath>..\lib\net8.0\IDSImaging.Peak.IPL.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="VL.Core" />
    <Using Include="VL.Core.Import" />
    <Using Include="VL.Lib.Collections" />
    <Using Include="Stride.Core.Mathematics" />
  </ItemGroup>

</Project>
